#!/usr/bin/env bash

set -a
. /etc/mfd-kiosk/kiosk.env
set +a

PROFILE="${XDG_RUNTIME_DIR}/mfd-firefox-profile"
rm -rf "$PROFILE"
mkdir -p "$PROFILE"
install -m 644 /etc/mfd-kiosk/firefox/user.js "$PROFILE/user.js"

while true; do
  ${BROWSER_BIN} \
    --profile "$PROFILE" \
    --kiosk \
    "${KIOSK_URL}"

  sleep 5
done &
